### ISSUE TITLE
Cannot Access EZ_ADJUST and IN START Menus

### ISSUE THREAD

**Issue by thirdgarcia** [ubaransel/lgcommander#10]
Hi, 

I tried to execute 255 and 251 but it returns nothing... My tv is LG LA6200 thanks

**Comment by ubaransel** [comment]
LA6200 is classified as "Smart TVs which are released in 2012 or later."
Their menus are either non-existent or unknown (secret).
Please read the README, especially:
"LG Smart TVs which are released in 2012 or later. "

**Comment by ubaransel** [comment]
LA6200 is classified as "Smart TVs which are released in 2012 or later."
Their menus are either non-existent or unknown (secret).
Please read the README, especially:
"Newer LG Smart TV (year 2012) models:"
