### ISSUE TITLE
Under which license is your script?

### ISSUE THREAD

**Issue by ypid** [ubaransel/lgcommander#8]
Hi

Have you thought putting the project under a license? I did not find any … I personally would go for [AGPLv3](https://en.wikipedia.org/wiki/Affero_General_Public_License). Is that OK with you?

**Comment by ubaransel** [comment]
Added LICENCE.txt

**Comment by ypid** [comment]
Thanks for the clarification. I [cherry-picked this commit](https://github.com/ypid/lgcommander/commit/6f016c53c8432ed6e71197460cb874635f2ad0ff) into my fork.
